jobs:
  build-test:
    uses: airbnb/RxGroups/.github/workflows/build_test.yml@master
  deploy-snapshot:
    needs: build-test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout RxGroups
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: liberica
        java-version: '8'
    - continue-on-error: true
      name: NDK workaround
      run: mkdir -p $ANDROID_HOME/ndk-bundle/toolchains/mips64el-linux-android/prebuilt/linux-x86_64
    - continue-on-error: true
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      name: Create sytem gradle.properties
      run: 'mkdir -p ~/.gradle/

        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV

        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

        '
      shell: bash
    - continue-on-error: true
      name: Deploy new snapshot of RxGroups
      run: ./gradlew uploadArchives
      shell: bash
name: Deploy snapshot
on:
  repository_dispatch:
    types: trigger-ga___deploy_snapshot.yml
